<?php
/**
 * ZonecryptokeyApi
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace insidieux\PowerDnsClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use insidieux\PowerDnsClient\ApiException;
use insidieux\PowerDnsClient\Configuration;
use insidieux\PowerDnsClient\HeaderSelector;
use insidieux\PowerDnsClient\ObjectSerializer;

/**
 * ZonecryptokeyApi Class Doc Comment
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonecryptokeyApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $configuration;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->configuration = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    /**
     * Operation createCryptokey
     *
     * Creates a Cryptokey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId zoneId (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey Add a Cryptokey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \insidieux\PowerDnsClient\Model\Cryptokey
     */
    public function createCryptokey($serverId, $zoneId, $cryptokey)
    {
        list($response) = $this->createCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokey);
        return $response;
    }

    /**
     * Operation createCryptokeyWithHttpInfo
     *
     * Creates a Cryptokey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey Add a Cryptokey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \insidieux\PowerDnsClient\Model\Cryptokey, HTTP status code, HTTP response headers (array of strings)
     */
    public function createCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokey)
    {
        $request = $this->createCryptokeyRequest($serverId, $zoneId, $cryptokey);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 201:
                    if ('\insidieux\PowerDnsClient\Model\Cryptokey' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\insidieux\PowerDnsClient\Model\Cryptokey', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\insidieux\PowerDnsClient\Model\Cryptokey';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\insidieux\PowerDnsClient\Model\Cryptokey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createCryptokeyAsync
     *
     * Creates a Cryptokey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey Add a Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCryptokeyAsync($serverId, $zoneId, $cryptokey)
    {
        return $this->createCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createCryptokeyAsyncWithHttpInfo
     *
     * Creates a Cryptokey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey Add a Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokey)
    {
        $returnType = '\insidieux\PowerDnsClient\Model\Cryptokey';
        $request = $this->createCryptokeyRequest($serverId, $zoneId, $cryptokey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createCryptokey'
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey Add a Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createCryptokeyRequest($serverId, $zoneId, $cryptokey)
    {
        // verify the required parameter 'serverId' is set
        if ($serverId === null || (is_array($serverId) && count($serverId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serverId when calling createCryptokey'
            );
        }
        // verify the required parameter 'zoneId' is set
        if ($zoneId === null || (is_array($zoneId) && count($zoneId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zoneId when calling createCryptokey'
            );
        }
        // verify the required parameter 'cryptokey' is set
        if ($cryptokey === null || (is_array($cryptokey) && count($cryptokey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cryptokey when calling createCryptokey'
            );
        }

        $resourcePath = '/servers/{server_id}/zones/{zone_id}/cryptokeys';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($serverId !== null) {
            $resourcePath = str_replace(
                '{' . 'server_id' . '}',
                ObjectSerializer::toPathValue($serverId),
                $resourcePath
            );
        }
        // path params
        if ($zoneId !== null) {
            $resourcePath = str_replace(
                '{' . 'zone_id' . '}',
                ObjectSerializer::toPathValue($zoneId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($cryptokey)) {
            $_tempBody = $cryptokey;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->configuration->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->configuration->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->configuration->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->configuration->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteCryptokey
     *
     * This method deletes a key specified by cryptokey_id.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the Cryptokey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteCryptokey($serverId, $zoneId, $cryptokeyId)
    {
        $this->deleteCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokeyId);
    }

    /**
     * Operation deleteCryptokeyWithHttpInfo
     *
     * This method deletes a key specified by cryptokey_id.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the Cryptokey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokeyId)
    {
        $request = $this->deleteCryptokeyRequest($serverId, $zoneId, $cryptokeyId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteCryptokeyAsync
     *
     * This method deletes a key specified by cryptokey_id.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteCryptokeyAsync($serverId, $zoneId, $cryptokeyId)
    {
        return $this->deleteCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokeyId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteCryptokeyAsyncWithHttpInfo
     *
     * This method deletes a key specified by cryptokey_id.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokeyId)
    {
        $returnType = '';
        $request = $this->deleteCryptokeyRequest($serverId, $zoneId, $cryptokeyId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteCryptokey'
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteCryptokeyRequest($serverId, $zoneId, $cryptokeyId)
    {
        // verify the required parameter 'serverId' is set
        if ($serverId === null || (is_array($serverId) && count($serverId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serverId when calling deleteCryptokey'
            );
        }
        // verify the required parameter 'zoneId' is set
        if ($zoneId === null || (is_array($zoneId) && count($zoneId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zoneId when calling deleteCryptokey'
            );
        }
        // verify the required parameter 'cryptokeyId' is set
        if ($cryptokeyId === null || (is_array($cryptokeyId) && count($cryptokeyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cryptokeyId when calling deleteCryptokey'
            );
        }

        $resourcePath = '/servers/{server_id}/zones/{zone_id}/cryptokeys/{cryptokey_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($serverId !== null) {
            $resourcePath = str_replace(
                '{' . 'server_id' . '}',
                ObjectSerializer::toPathValue($serverId),
                $resourcePath
            );
        }
        // path params
        if ($zoneId !== null) {
            $resourcePath = str_replace(
                '{' . 'zone_id' . '}',
                ObjectSerializer::toPathValue($zoneId),
                $resourcePath
            );
        }
        // path params
        if ($cryptokeyId !== null) {
            $resourcePath = str_replace(
                '{' . 'cryptokey_id' . '}',
                ObjectSerializer::toPathValue($cryptokeyId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->configuration->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->configuration->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->configuration->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->configuration->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCryptokey
     *
     * Returns all data about the CryptoKey, including the privatekey.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the CryptoKey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \insidieux\PowerDnsClient\Model\Cryptokey
     */
    public function getCryptokey($serverId, $zoneId, $cryptokeyId)
    {
        list($response) = $this->getCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokeyId);
        return $response;
    }

    /**
     * Operation getCryptokeyWithHttpInfo
     *
     * Returns all data about the CryptoKey, including the privatekey.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the CryptoKey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \insidieux\PowerDnsClient\Model\Cryptokey, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokeyId)
    {
        $request = $this->getCryptokeyRequest($serverId, $zoneId, $cryptokeyId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\insidieux\PowerDnsClient\Model\Cryptokey' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\insidieux\PowerDnsClient\Model\Cryptokey', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\insidieux\PowerDnsClient\Model\Cryptokey';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\insidieux\PowerDnsClient\Model\Cryptokey',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCryptokeyAsync
     *
     * Returns all data about the CryptoKey, including the privatekey.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the CryptoKey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCryptokeyAsync($serverId, $zoneId, $cryptokeyId)
    {
        return $this->getCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokeyId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCryptokeyAsyncWithHttpInfo
     *
     * Returns all data about the CryptoKey, including the privatekey.
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the CryptoKey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokeyId)
    {
        $returnType = '\insidieux\PowerDnsClient\Model\Cryptokey';
        $request = $this->getCryptokeyRequest($serverId, $zoneId, $cryptokeyId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCryptokey'
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     * @param  string $cryptokeyId The id value of the CryptoKey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getCryptokeyRequest($serverId, $zoneId, $cryptokeyId)
    {
        // verify the required parameter 'serverId' is set
        if ($serverId === null || (is_array($serverId) && count($serverId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serverId when calling getCryptokey'
            );
        }
        // verify the required parameter 'zoneId' is set
        if ($zoneId === null || (is_array($zoneId) && count($zoneId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zoneId when calling getCryptokey'
            );
        }
        // verify the required parameter 'cryptokeyId' is set
        if ($cryptokeyId === null || (is_array($cryptokeyId) && count($cryptokeyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cryptokeyId when calling getCryptokey'
            );
        }

        $resourcePath = '/servers/{server_id}/zones/{zone_id}/cryptokeys/{cryptokey_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($serverId !== null) {
            $resourcePath = str_replace(
                '{' . 'server_id' . '}',
                ObjectSerializer::toPathValue($serverId),
                $resourcePath
            );
        }
        // path params
        if ($zoneId !== null) {
            $resourcePath = str_replace(
                '{' . 'zone_id' . '}',
                ObjectSerializer::toPathValue($zoneId),
                $resourcePath
            );
        }
        // path params
        if ($cryptokeyId !== null) {
            $resourcePath = str_replace(
                '{' . 'cryptokey_id' . '}',
                ObjectSerializer::toPathValue($cryptokeyId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->configuration->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->configuration->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->configuration->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->configuration->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCryptokeys
     *
     * Get all CryptoKeys for a zone, except the privatekey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \insidieux\PowerDnsClient\Model\Cryptokey[]
     */
    public function listCryptokeys($serverId, $zoneId)
    {
        list($response) = $this->listCryptokeysWithHttpInfo($serverId, $zoneId);
        return $response;
    }

    /**
     * Operation listCryptokeysWithHttpInfo
     *
     * Get all CryptoKeys for a zone, except the privatekey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \insidieux\PowerDnsClient\Model\Cryptokey[], HTTP status code, HTTP response headers (array of strings)
     */
    public function listCryptokeysWithHttpInfo($serverId, $zoneId)
    {
        $request = $this->listCryptokeysRequest($serverId, $zoneId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\insidieux\PowerDnsClient\Model\Cryptokey[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\insidieux\PowerDnsClient\Model\Cryptokey[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\insidieux\PowerDnsClient\Model\Cryptokey[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\insidieux\PowerDnsClient\Model\Cryptokey[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listCryptokeysAsync
     *
     * Get all CryptoKeys for a zone, except the privatekey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCryptokeysAsync($serverId, $zoneId)
    {
        return $this->listCryptokeysAsyncWithHttpInfo($serverId, $zoneId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCryptokeysAsyncWithHttpInfo
     *
     * Get all CryptoKeys for a zone, except the privatekey
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCryptokeysAsyncWithHttpInfo($serverId, $zoneId)
    {
        $returnType = '\insidieux\PowerDnsClient\Model\Cryptokey[]';
        $request = $this->listCryptokeysRequest($serverId, $zoneId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCryptokeys'
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId The id of the zone to retrieve (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listCryptokeysRequest($serverId, $zoneId)
    {
        // verify the required parameter 'serverId' is set
        if ($serverId === null || (is_array($serverId) && count($serverId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serverId when calling listCryptokeys'
            );
        }
        // verify the required parameter 'zoneId' is set
        if ($zoneId === null || (is_array($zoneId) && count($zoneId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zoneId when calling listCryptokeys'
            );
        }

        $resourcePath = '/servers/{server_id}/zones/{zone_id}/cryptokeys';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($serverId !== null) {
            $resourcePath = str_replace(
                '{' . 'server_id' . '}',
                ObjectSerializer::toPathValue($serverId),
                $resourcePath
            );
        }
        // path params
        if ($zoneId !== null) {
            $resourcePath = str_replace(
                '{' . 'zone_id' . '}',
                ObjectSerializer::toPathValue($zoneId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->configuration->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->configuration->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->configuration->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->configuration->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation modifyCryptokey
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId zoneId (required)
     * @param  string $cryptokeyId Cryptokey to manipulate (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey the Cryptokey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function modifyCryptokey($serverId, $zoneId, $cryptokeyId, $cryptokey)
    {
        $this->modifyCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokeyId, $cryptokey);
    }

    /**
     * Operation modifyCryptokeyWithHttpInfo
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  string $cryptokeyId Cryptokey to manipulate (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey the Cryptokey (required)
     *
     * @throws \insidieux\PowerDnsClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function modifyCryptokeyWithHttpInfo($serverId, $zoneId, $cryptokeyId, $cryptokey)
    {
        $request = $this->modifyCryptokeyRequest($serverId, $zoneId, $cryptokeyId, $cryptokey);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation modifyCryptokeyAsync
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  string $cryptokeyId Cryptokey to manipulate (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey the Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function modifyCryptokeyAsync($serverId, $zoneId, $cryptokeyId, $cryptokey)
    {
        return $this->modifyCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokeyId, $cryptokey)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation modifyCryptokeyAsyncWithHttpInfo
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  string $cryptokeyId Cryptokey to manipulate (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey the Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function modifyCryptokeyAsyncWithHttpInfo($serverId, $zoneId, $cryptokeyId, $cryptokey)
    {
        $returnType = '';
        $request = $this->modifyCryptokeyRequest($serverId, $zoneId, $cryptokeyId, $cryptokey);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'modifyCryptokey'
     *
     * @param  string $serverId The id of the server to retrieve (required)
     * @param  string $zoneId (required)
     * @param  string $cryptokeyId Cryptokey to manipulate (required)
     * @param  \insidieux\PowerDnsClient\Model\Cryptokey $cryptokey the Cryptokey (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function modifyCryptokeyRequest($serverId, $zoneId, $cryptokeyId, $cryptokey)
    {
        // verify the required parameter 'serverId' is set
        if ($serverId === null || (is_array($serverId) && count($serverId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $serverId when calling modifyCryptokey'
            );
        }
        // verify the required parameter 'zoneId' is set
        if ($zoneId === null || (is_array($zoneId) && count($zoneId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zoneId when calling modifyCryptokey'
            );
        }
        // verify the required parameter 'cryptokeyId' is set
        if ($cryptokeyId === null || (is_array($cryptokeyId) && count($cryptokeyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cryptokeyId when calling modifyCryptokey'
            );
        }
        // verify the required parameter 'cryptokey' is set
        if ($cryptokey === null || (is_array($cryptokey) && count($cryptokey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cryptokey when calling modifyCryptokey'
            );
        }

        $resourcePath = '/servers/{server_id}/zones/{zone_id}/cryptokeys/{cryptokey_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($serverId !== null) {
            $resourcePath = str_replace(
                '{' . 'server_id' . '}',
                ObjectSerializer::toPathValue($serverId),
                $resourcePath
            );
        }
        // path params
        if ($zoneId !== null) {
            $resourcePath = str_replace(
                '{' . 'zone_id' . '}',
                ObjectSerializer::toPathValue($zoneId),
                $resourcePath
            );
        }
        // path params
        if ($cryptokeyId !== null) {
            $resourcePath = str_replace(
                '{' . 'cryptokey_id' . '}',
                ObjectSerializer::toPathValue($cryptokeyId),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($cryptokey)) {
            $_tempBody = $cryptokey;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->configuration->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->configuration->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->configuration->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->configuration->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->configuration->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->configuration->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->configuration->getDebugFile());
            }
        }

        return $options;
    }
}
