<?php
/**
 * CryptokeyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace insidieux\PowerDnsClient;

/**
 * CryptokeyTest Class Doc Comment
 *
 * @category    Class
 * @description Describes a DNSSEC cryptographic key
 * @package     insidieux\PowerDnsClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CryptokeyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Cryptokey"
     */
    public function testCryptokey()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "keytype"
     */
    public function testPropertyKeytype()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "dnskey"
     */
    public function testPropertyDnskey()
    {
    }

    /**
     * Test attribute "ds"
     */
    public function testPropertyDs()
    {
    }

    /**
     * Test attribute "privatekey"
     */
    public function testPropertyPrivatekey()
    {
    }

    /**
     * Test attribute "algorithm"
     */
    public function testPropertyAlgorithm()
    {
    }

    /**
     * Test attribute "bits"
     */
    public function testPropertyBits()
    {
    }
}
