<?php
/**
 * ZoneTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace insidieux\PowerDnsClient;

/**
 * ZoneTest Class Doc Comment
 *
 * @category    Class
 * @description This represents an authoritative DNS Zone.
 * @package     insidieux\PowerDnsClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ZoneTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Zone"
     */
    public function testZone()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "rrsets"
     */
    public function testPropertyRrsets()
    {
    }

    /**
     * Test attribute "serial"
     */
    public function testPropertySerial()
    {
    }

    /**
     * Test attribute "notifiedSerial"
     */
    public function testPropertyNotifiedSerial()
    {
    }

    /**
     * Test attribute "masters"
     */
    public function testPropertyMasters()
    {
    }

    /**
     * Test attribute "dnssec"
     */
    public function testPropertyDnssec()
    {
    }

    /**
     * Test attribute "nsec3param"
     */
    public function testPropertyNsec3param()
    {
    }

    /**
     * Test attribute "nsec3narrow"
     */
    public function testPropertyNsec3narrow()
    {
    }

    /**
     * Test attribute "presigned"
     */
    public function testPropertyPresigned()
    {
    }

    /**
     * Test attribute "soaEdit"
     */
    public function testPropertySoaEdit()
    {
    }

    /**
     * Test attribute "soaEditApi"
     */
    public function testPropertySoaEditApi()
    {
    }

    /**
     * Test attribute "apiRectify"
     */
    public function testPropertyApiRectify()
    {
    }

    /**
     * Test attribute "zone"
     */
    public function testPropertyZone()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "nameservers"
     */
    public function testPropertyNameservers()
    {
    }
}
