<?php
/**
 * ServersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace insidieux\PowerDnsClient;

use \insidieux\PowerDnsClient\Configuration;
use \insidieux\PowerDnsClient\ApiException;
use \insidieux\PowerDnsClient\ObjectSerializer;

/**
 * ServersApiTest Class Doc Comment
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cacheFlushByName
     *
     * Flush a cache-entry by name.
     *
     */
    public function testCacheFlushByName()
    {
    }

    /**
     * Test case for listServer
     *
     * List a server.
     *
     */
    public function testListServer()
    {
    }

    /**
     * Test case for listServers
     *
     * List all servers.
     *
     */
    public function testListServers()
    {
    }
}
