<?php
/**
 * ZonemetadataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace insidieux\PowerDnsClient;

use \insidieux\PowerDnsClient\Configuration;
use \insidieux\PowerDnsClient\ApiException;
use \insidieux\PowerDnsClient\ObjectSerializer;

/**
 * ZonemetadataApiTest Class Doc Comment
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonemetadataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMetadata
     *
     * Creates a set of metadata entries.
     *
     */
    public function testCreateMetadata()
    {
    }

    /**
     * Test case for deleteMetadata
     *
     * Delete all items of a single kind of domain metadata..
     *
     */
    public function testDeleteMetadata()
    {
    }

    /**
     * Test case for getMetadata
     *
     * Get the content of a single kind of domain metadata as a list of MetaData objects..
     *
     */
    public function testGetMetadata()
    {
    }

    /**
     * Test case for listMetadata
     *
     * Get all the MetaData associated with the zone..
     *
     */
    public function testListMetadata()
    {
    }

    /**
     * Test case for modifyMetadata
     *
     * Modify the content of a single kind of domain metadata..
     *
     */
    public function testModifyMetadata()
    {
    }
}
