<?php
/**
 * ZonesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace insidieux\PowerDnsClient;

use \insidieux\PowerDnsClient\Configuration;
use \insidieux\PowerDnsClient\ApiException;
use \insidieux\PowerDnsClient\ObjectSerializer;

/**
 * ZonesApiTest Class Doc Comment
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for axfrExportZone
     *
     * Returns the zone in AXFR format..
     *
     */
    public function testAxfrExportZone()
    {
    }

    /**
     * Test case for axfrRetrieveZone
     *
     * Retrieve slave zone from its master..
     *
     */
    public function testAxfrRetrieveZone()
    {
    }

    /**
     * Test case for checkZone
     *
     * Verify zone contents/configuration..
     *
     */
    public function testCheckZone()
    {
    }

    /**
     * Test case for createZone
     *
     * Creates a new domain, returns the Zone on creation..
     *
     */
    public function testCreateZone()
    {
    }

    /**
     * Test case for deleteZone
     *
     * Deletes this zone, all attached metadata and rrsets..
     *
     */
    public function testDeleteZone()
    {
    }

    /**
     * Test case for listZone
     *
     * zone managed by a server.
     *
     */
    public function testListZone()
    {
    }

    /**
     * Test case for listZones
     *
     * List all Zones in a server.
     *
     */
    public function testListZones()
    {
    }

    /**
     * Test case for notifyZone
     *
     * Send a DNS NOTIFY to all slaves..
     *
     */
    public function testNotifyZone()
    {
    }

    /**
     * Test case for patchZone
     *
     * Creates/modifies/deletes RRsets present in the payload and their comments. Returns 204 No Content on success..
     *
     */
    public function testPatchZone()
    {
    }

    /**
     * Test case for putZone
     *
     * Modifies basic zone data (metadata)..
     *
     */
    public function testPutZone()
    {
    }

    /**
     * Test case for rectifyZone
     *
     * Rectify the zone data..
     *
     */
    public function testRectifyZone()
    {
    }
}
