<?php
/**
 * ZonecryptokeyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PowerDNS Authoritative HTTP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.13
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace insidieux\PowerDnsClient;

use \insidieux\PowerDnsClient\Configuration;
use \insidieux\PowerDnsClient\ApiException;
use \insidieux\PowerDnsClient\ObjectSerializer;

/**
 * ZonecryptokeyApiTest Class Doc Comment
 *
 * @category Class
 * @package  insidieux\PowerDnsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ZonecryptokeyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCryptokey
     *
     * Creates a Cryptokey.
     *
     */
    public function testCreateCryptokey()
    {
    }

    /**
     * Test case for deleteCryptokey
     *
     * This method deletes a key specified by cryptokey_id..
     *
     */
    public function testDeleteCryptokey()
    {
    }

    /**
     * Test case for getCryptokey
     *
     * Returns all data about the CryptoKey, including the privatekey..
     *
     */
    public function testGetCryptokey()
    {
    }

    /**
     * Test case for listCryptokeys
     *
     * Get all CryptoKeys for a zone, except the privatekey.
     *
     */
    public function testListCryptokeys()
    {
    }

    /**
     * Test case for modifyCryptokey
     *
     * This method (de)activates a key from zone_name specified by cryptokey_id.
     *
     */
    public function testModifyCryptokey()
    {
    }
}
